// dcg-omp-extension: generated by `dcg install --omp` — do not edit.
// Routes every Oh My Pi bash tool call through dcg (Destructive Command Guard)
// before execution. Docs: https://github.com/Dicklesworthstone/destructive_command_guard
import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";
import { settings } from "@oh-my-pi/pi-coding-agent/config/settings";
import { procmgr } from "@oh-my-pi/pi-utils";
import { resolveToCwd } from "@oh-my-pi/pi-coding-agent/tools/path-utils";
import { extractLeadingCdTarget } from "@oh-my-pi/pi-coding-agent/tools/shell-tokenize";

// This marker-owned install artifact binds the guard to the install-time
// absolute dcg pathname. It does not attest the bytes later resolved there;
// ambient environment must not redirect the pathname.
const DCG_BIN = "/Users/hose/.local/bin/dcg";
const DCG_CHILD_TIMEOUT_MS = 30000;
export const DCG_CHILD_PIPE_DRAIN_GRACE_MS = 250;
export const DCG_CHILD_OBSERVATION_TIMEOUT_MS = 30500;
export const DCG_STDOUT_MAX_BYTES = 786486;
export const DCG_STDERR_MAX_BYTES = 65536;
export const DCG_STDIN_CHUNK_CODE_UNITS = 16384;
const DCG_SIGNAL_CODE_MAX_CHARS = 64;
type DcgChildOutcome = "spawn-throw" | "exit-0" | "exit-1" | "exit-2" | "exit-other" | "signal";
type DcgParsedVerdict = "empty" | "malformed" | "allow" | "deny" | "ask" | "indeterminate" | "unknown";
type DcgBridgeAction = "allow" | "block" | "infrastructure";
type DcgParsedOutput = {
  verdict: DcgParsedVerdict;
  reason?: string;
  ruleId?: string;
  framedBlockingWitness?: true;
};
type DcgBoundedText = { text: string; overflowed: boolean; readFailure?: string };
type DcgObservationBoundary = "pipe-drain" | "hard-deadline";
type DcgChildObservationResults = {
  stdoutResult: PromiseSettledResult<DcgBoundedText>;
  stderrResult: PromiseSettledResult<DcgBoundedText>;
  exitResult: PromiseSettledResult<unknown>;
  boundary?: DcgObservationBoundary;
  killFailure?: string;
};
type OmpBashToolInput = { command?: unknown; cwd?: unknown; async?: unknown; pty?: unknown };
type OmpToolCallClassification =
  | { kind: "other-tool" }
  | { kind: "invalid-bash" }
  | { kind: "bash"; input: OmpBashToolInput; command: string };

const BLOCKING_DECISIONS: ReadonlySet<DcgParsedVerdict> = new Set<DcgParsedVerdict>(["deny", "ask", "indeterminate"]);
const DCG_OBSERVATION_ABORTED = Symbol("dcg-child-observation-aborted");
// Bun exposes no stdout when spawn itself throws. That runtime catch remains a
// visible infrastructure fail-open; this total row makes the pure classifier
// exhaustive for replay/model tests and preserves deny-like monotonicity.
const DCG_CHILD_TRANSITIONS: Record<DcgChildOutcome, Record<DcgParsedVerdict, DcgBridgeAction>> = {
  "spawn-throw": { empty: "infrastructure", malformed: "infrastructure", allow: "infrastructure", deny: "block", ask: "block", indeterminate: "block", unknown: "infrastructure" },
  "exit-0": { empty: "allow", malformed: "allow", allow: "allow", deny: "block", ask: "block", indeterminate: "block", unknown: "allow" },
  "exit-1": { empty: "block", malformed: "block", allow: "block", deny: "block", ask: "block", indeterminate: "block", unknown: "block" },
  "exit-2": { empty: "allow", malformed: "allow", allow: "allow", deny: "block", ask: "block", indeterminate: "block", unknown: "allow" },
  "exit-other": { empty: "infrastructure", malformed: "infrastructure", allow: "infrastructure", deny: "block", ask: "block", indeterminate: "block", unknown: "infrastructure" },
  "signal": { empty: "infrastructure", malformed: "infrastructure", allow: "infrastructure", deny: "block", ask: "block", indeterminate: "block", unknown: "infrastructure" },
};

// OMP's agent loop schema-validates built-in bash arguments before emitting
// tool_call, but direct/non-loop wrapper dispatch is also public. Preserve the
// exact tool-name boundary and fail closed only when an identifiable bash call
// violates the required object-with-string-command shape.
export function classifyOmpToolCall(event: unknown): OmpToolCallClassification {
  if (typeof event !== "object" || event === null || Array.isArray(event)) return { kind: "other-tool" };
  const record = event as Record<string, unknown>;
  if (record.toolName !== "bash") return { kind: "other-tool" };
  const input = record.input;
  if (typeof input !== "object" || input === null || Array.isArray(input)) return { kind: "invalid-bash" };
  const toolInput = input as OmpBashToolInput;
  if (typeof toolInput.command !== "string") return { kind: "invalid-bash" };
  return { kind: "bash", input: toolInput, command: toolInput.command };
}

function parseDcgJson(text: string): DcgParsedOutput {
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    return { verdict: "malformed" };
  }
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    return { verdict: "unknown" };
  }

  const record = raw as Record<string, unknown>;
  const decision = record.decision;
  const verdict: DcgParsedVerdict =
    decision === "allow" ||
    decision === "deny" ||
    decision === "ask" ||
    decision === "indeterminate"
      ? decision
      : "unknown";
  return {
    verdict,
    reason: typeof record.reason === "string" ? record.reason : undefined,
    ruleId: typeof record.rule_id === "string" ? record.rule_id : undefined,
  };
}

function parseDcgOutput(stdoutText: string): DcgParsedOutput {
  const text = stdoutText.trim();
  if (!text) return { verdict: "empty" };

  const parsed = parseDcgJson(text);
  if (parsed.verdict !== "malformed") return parsed;

  // The private Rust producer emits exactly one compact JSON object followed
  // by LF. If later bytes corrupt the aggregate, retain any independently
  // parseable, delimiter-complete blocking frame as an absorbing witness.
  // Never recover allow, never parse an unterminated suffix, and never infer a
  // JSON prefix from same-line junk. OmpBridgeTestOutput declares `decision`
  // first, so its exact prefixes cheaply skip arbitrary diagnostic lines
  // before paying for JSON.parse on this cold path.
  let frameStart = 0;
  while (true) {
    const frameEnd = stdoutText.indexOf("\n", frameStart);
    if (frameEnd < 0) break;
    const frame = stdoutText.slice(frameStart, frameEnd).trim();
    const mightBlock =
      frame.startsWith('{"decision":"deny"') ||
      frame.startsWith('{"decision":"ask"') ||
      frame.startsWith('{"decision":"indeterminate"');
    if (mightBlock) {
      const candidate = parseDcgJson(frame);
      if (BLOCKING_DECISIONS.has(candidate.verdict)) {
        return { ...candidate, framedBlockingWitness: true };
      }
    }
    frameStart = frameEnd + 1;
  }
  return parsed;
}

export function classifyDcgChild(
  outcome: DcgChildOutcome,
  stdoutText: string,
): { action: DcgBridgeAction; output: DcgParsedOutput } {
  const output = parseDcgOutput(stdoutText);
  return { action: DCG_CHILD_TRANSITIONS[outcome][output.verdict], output };
}

function isDcgSignalName(signalCode: string): boolean {
  if (
    signalCode.length <= 3 ||
    signalCode.length > DCG_SIGNAL_CODE_MAX_CHARS ||
    !signalCode.startsWith("SIG")
  ) return false;
  for (let index = 3; index < signalCode.length; index += 1) {
    const code = signalCode.charCodeAt(index);
    if (!((code >= 0x41 && code <= 0x5a) || (code >= 0x30 && code <= 0x39))) return false;
  }
  return true;
}

function isDcgSignalCode(signalCode: unknown): signalCode is string | number {
  return (
    (typeof signalCode === "string" && isDcgSignalName(signalCode)) ||
    (typeof signalCode === "number" && Number.isInteger(signalCode) && signalCode > 0)
  );
}

function isDcgExitCode(exitCode: unknown): exitCode is number {
  return typeof exitCode === "number" && Number.isInteger(exitCode) && exitCode >= 0;
}

export function childOutcomeFromTermination(
  exitCode: unknown,
  signalCode: unknown,
): DcgChildOutcome {
  // Preserve dcg's independent blocking status even under an impossible or
  // future runtime shape that reports both exit 1 and a signal.
  if (exitCode === 1) return "exit-1";
  // Bun's `.exited` resolves to 128 + signal on POSIX, which is identical to
  // an ordinary process that chose that numeric exit. `signalCode`, populated
  // after exit, is the authoritative provenance discriminator.
  if (isDcgSignalCode(signalCode)) return "signal";
  if (exitCode === 0) return "exit-0";
  if (exitCode === 2) return "exit-2";
  return "exit-other";
}

function boundedDiagnosticText(text: string): string {
  const suffix = "\n[dcg: diagnostic truncated]";
  const buffer = new Uint8Array(DCG_STDERR_MAX_BYTES - suffix.length);
  const encoded = new TextEncoder().encodeInto(text, buffer);
  if (encoded.read === text.length) return text;
  // `stream: true` deliberately withholds a code point split by the byte cap.
  const prefix = new TextDecoder().decode(buffer.subarray(0, encoded.written), { stream: true });
  return prefix + suffix;
}

function describeChildCollectionFailure(reason: unknown): string {
  try {
    return boundedDiagnosticText(String(reason));
  } catch {
    return "<unprintable rejection>";
  }
}

function childTerminationDetail(exitCode: unknown, signalCode: unknown): string {
  if (isDcgSignalCode(signalCode)) return ` (signal ${signalCode})`;
  if (isDcgExitCode(exitCode)) return ` (exit ${exitCode})`;
  if (exitCode === undefined) return " (exit status unavailable)";
  if (exitCode === null) return " (exit status null)";
  // Never echo an invalid runtime value: control characters or a hostile
  // `toString` implementation could forge diagnostics.
  return ` (exit status invalid: ${typeof exitCode})`;
}

function observeChildCapability<T>(collect: () => Promise<T>): Promise<T> {
  try {
    return collect();
  } catch (reason) {
    return Promise.reject(reason);
  }
}

export function commandUtf8Stream(command: string): ReadableStream<Uint8Array> {
  let offset = 0;
  const text = new ReadableStream<string>({
    pull(controller): void {
      if (offset >= command.length) {
        controller.close();
        return;
      }
      let end = Math.min(offset + DCG_STDIN_CHUNK_CODE_UNITS, command.length);
      // JavaScript slices by UTF-16 code unit. Keep an astral scalar together
      // when the nominal boundary lands between its surrogate pair.
      if (
        end < command.length
        && command.charCodeAt(end - 1) >= 0xd800
        && command.charCodeAt(end - 1) <= 0xdbff
        && command.charCodeAt(end) >= 0xdc00
        && command.charCodeAt(end) <= 0xdfff
      ) {
        end += 1;
      }
      controller.enqueue(command.slice(offset, end));
      offset = end;
    },
  });
  // TextEncoderStream carries a valid surrogate pair across chunk boundaries,
  // preserving its UTF-8 scalar without a command-sized allocation. As the
  // Encoding Standard requires, both this path and `TextEncoder.encode()`
  // canonicalize an unpaired UTF-16 surrogate to U+FFFD.
  return text.pipeThrough(new TextEncoderStream());
}

export function commandStdin(command: string): Uint8Array | ReadableStream<Uint8Array> {
  // Preserve Bun's low-overhead direct-byte path for ordinary commands. Only
  // configured-large input pays the stream/object cost needed to bound peak
  // encoding allocation.
  return command.length <= DCG_STDIN_CHUNK_CODE_UNITS
    ? new TextEncoder().encode(command)
    : commandUtf8Stream(command);
}

export async function collectBoundedText(
  stream: ReadableStream<Uint8Array>,
  maxBytes: number,
  abortSignal?: AbortSignal,
): Promise<DcgBoundedText> {
  // Grow only with observed output. Compact allow/deny envelopes stay compact
  // instead of reserving the entire safety cap on every guarded command.
  let retained = new Uint8Array(0);
  let retainedBytes = 0;
  let overflowed = false;
  let readFailure: string | undefined;
  const reader = stream.getReader();
  let cancellationRequested = false;
  const cancelReader = (): void => {
    if (cancellationRequested) return;
    cancellationRequested = true;
    try {
      // WHATWG stream cancellation settles pending reads. Attach a rejection
      // handler even though the result is diagnostic-only, so a hostile or
      // future stream implementation cannot create a late unhandled rejection.
      void reader.cancel(DCG_OBSERVATION_ABORTED).catch(() => {});
    } catch {
      // A synchronous cancellation fault is a runtime contract violation.
      // The independently bounded child observation still reports its fixed
      // deadline diagnostic if the standard pending-read settlement occurs.
    }
  };
  if (abortSignal?.aborted) cancelReader();
  else abortSignal?.addEventListener("abort", cancelReader, { once: true });
  try {
    while (true) {
      const next = await reader.read();
      if (next.done) break;
      const chunk = next.value;
      const available = maxBytes - retainedBytes;
      const keep = Math.min(available, chunk.byteLength);
      if (keep > 0) {
        const needed = retainedBytes + keep;
        if (needed > retained.byteLength) {
          const doubled = retained.byteLength === 0 ? needed : retained.byteLength * 2;
          const capacity = Math.min(maxBytes, Math.max(needed, doubled));
          const grown = new Uint8Array(capacity);
          grown.set(retained.subarray(0, retainedBytes));
          retained = grown;
        }
        retained.set(chunk.subarray(0, keep), retainedBytes);
        retainedBytes += keep;
      }
      if (keep < chunk.byteLength) overflowed = true;
    }
  } catch (reason) {
    // Preserve any complete verdict received before a stream fault. The fault
    // remains independently visible and cannot downgrade an overflow block.
    if (!cancellationRequested) readFailure = describeChildCollectionFailure(reason);
  } finally {
    abortSignal?.removeEventListener("abort", cancelReader);
    reader.releaseLock();
  }

  const bytes = retained.subarray(0, retainedBytes);
  // When the cap cuts a multi-byte scalar, streaming decode withholds that
  // incomplete suffix instead of manufacturing U+FFFD. At/below the cap the
  // final decode flushes normally, including chunks split inside a scalar.
  const text = overflowed
    ? new TextDecoder().decode(bytes, { stream: true })
    : new TextDecoder().decode(bytes);
  return { text, overflowed, readFailure };
}

function visibleStderrDetail(stderr: DcgBoundedText): string {
  const detail = stderr.text.trim();
  if (!stderr.overflowed) return detail;
  const suffix = `[dcg: stderr exceeded ${DCG_STDERR_MAX_BYTES}-byte display cap; additional bytes omitted]`;
  return detail ? `${detail}\n${suffix}` : suffix;
}

function observeChildCapabilityUntil<T>(
  capability: Promise<T>,
  abortSignal: AbortSignal,
): Promise<T> {
  if (abortSignal.aborted) return Promise.reject(DCG_OBSERVATION_ABORTED);
  return new Promise<T>((resolve, reject) => {
    let settled = false;
    const finishResolve = (value: T): void => {
      if (settled) return;
      settled = true;
      abortSignal.removeEventListener("abort", onAbort);
      resolve(value);
    };
    const finishReject = (reason: unknown): void => {
      if (settled) return;
      settled = true;
      abortSignal.removeEventListener("abort", onAbort);
      reject(reason);
    };
    const onAbort = (): void => finishReject(DCG_OBSERVATION_ABORTED);
    abortSignal.addEventListener("abort", onAbort, { once: true });
    // Both handlers remain attached even if the watchdog wins. A late
    // fulfillment or rejection is consumed rather than becoming unhandled.
    capability.then(finishResolve, finishReject);
  });
}

function killDcgChild(proc: Bun.ReadableSubprocess): string | undefined {
  try {
    proc.kill("SIGKILL");
    return undefined;
  } catch (reason) {
    return describeChildCollectionFailure(reason);
  }
}

async function observeDcgChild(proc: Bun.ReadableSubprocess): Promise<DcgChildObservationResults> {
  const observationAbort = new AbortController();
  const observationDeadline = performance.now() + DCG_CHILD_OBSERVATION_TIMEOUT_MS;
  let observationFinished = false;
  let boundary: DcgObservationBoundary | undefined;
  let killFailure: string | undefined;
  const abortObservation = (nextBoundary: DcgObservationBoundary, killChild: boolean): void => {
    if (observationFinished || observationAbort.signal.aborted) return;
    boundary = nextBoundary;
    if (killChild) killFailure = killDcgChild(proc);
    observationAbort.abort(DCG_OBSERVATION_ABORTED);
  };

  // Arm immediately after the successful spawn. This is independent of Bun's
  // native process timeout and therefore also bounds an exit observation that
  // never settles. Synchronous Bun.spawn/event-loop stalls remain outside any
  // in-process JavaScript timer's authority.
  let observationTimer = setTimeout(
    () => abortObservation("hard-deadline", true),
    DCG_CHILD_OBSERVATION_TIMEOUT_MS,
  );
  const rawExitObservation = observeChildCapability(() => proc.exited);
  const armPipeDrainDeadline = (killChild: boolean): void => {
    if (observationFinished || observationAbort.signal.aborted) return;
    if (killChild) killFailure = killDcgChild(proc);
    clearTimeout(observationTimer);
    const remainingHardBudget = Math.max(0, observationDeadline - performance.now());
    const pipeDrainWins = remainingHardBudget > DCG_CHILD_PIPE_DRAIN_GRACE_MS;
    observationTimer = setTimeout(
      () => abortObservation(pipeDrainWins ? "pipe-drain" : "hard-deadline", false),
      Math.min(DCG_CHILD_PIPE_DRAIN_GRACE_MS, remainingHardBudget),
    );
  };
  rawExitObservation.then(
    () => armPipeDrainDeadline(false),
    () => armPipeDrainDeadline(true),
  );

  try {
    const [stdoutResult, stderrResult, exitResult] = await Promise.allSettled([
      observeChildCapability(() => collectBoundedText(
        proc.stdout,
        DCG_STDOUT_MAX_BYTES,
        observationAbort.signal,
      )),
      observeChildCapability(() => collectBoundedText(
        proc.stderr,
        DCG_STDERR_MAX_BYTES,
        observationAbort.signal,
      )),
      observeChildCapabilityUntil(rawExitObservation, observationAbort.signal),
    ]);
    return { stdoutResult, stderrResult, exitResult, boundary, killFailure };
  } finally {
    observationFinished = true;
    clearTimeout(observationTimer);
  }
}

export default function dcgGuard(pi: ExtensionAPI): void {
  pi.on("tool_call", async (event, ctx) => {
    const toolCall = classifyOmpToolCall(event);
    if (toolCall.kind === "other-tool") return;
    if (toolCall.kind === "invalid-bash") {
      return {
        block: true,
        reason: "[dcg] OMP guard received malformed bash input (expected an object with a string command)",
      };
    }
    const { input: toolInput, command } = toolCall;
    // OMP's schema permits the empty string and its BashTool treats it as a
    // no-op. Preserve that exact case; every non-empty string, including
    // whitespace, still crosses the dcg decision boundary.
    if (command.length === 0) return;

    // Match OMP's BashTool filesystem-cwd derivation. Structured cwd wins;
    // when it is absent OMP extracts only its conservative
    // `cd <path> && ...` prefix. Reusing OMP's exported helpers keeps tilde,
    // absolute, relative, Windows-drive-alias, and bare-root semantics
    // synchronized upstream.
    // An internal protocol URL is expanded only later by BashTool, with state
    // this callback does not expose. resolveToCwd rejects it here, and the
    // catch fails closed rather than evaluating under an unrelated policy.
    let commandCwd: string;
    try {
      const structuredCwd = typeof toolInput?.cwd === "string" && toolInput.cwd
        ? toolInput.cwd
        : undefined;
      const requestedCwd = structuredCwd || extractLeadingCdTarget(command)?.path;
      commandCwd = requestedCwd ? resolveToCwd(requestedCwd, ctx.cwd) : ctx.cwd;
    } catch (err) {
      return {
        block: true,
        reason: `[dcg] OMP guard could not resolve the bash working directory safely: ${describeChildCollectionFailure(err)}`,
      };
    }

    // OMP executes ordinary and managed-async BashTool calls in its embedded
    // Brush shell, including on native Windows. Only an eligible local PTY
    // bypasses Brush for the configured external shell. Mirror OMP's route
    // predicate exactly: async wins before PTY, and PI_NO_PTY=1 disables PTY.
    // OMP does not expose its ClientBridge terminal capability to extensions;
    // ACP and JSON-RPC both report ctx.mode="rpc", so never guess from mode.
    let shellDialect: "posix" | "ps" | "cmd" = "posix";
    const usesLocalPty =
      toolInput?.pty === true && toolInput?.async !== true && ctx.hasUI && process.env.PI_NO_PTY !== "1";
    if (usesLocalPty) {
      try {
        const shell = settings.getShellConfig().shell;
        shellDialect = procmgr.isCmdShell(shell) ? "cmd" : procmgr.isPowerShell(shell) ? "ps" : "posix";
      } catch (err) {
        return {
          block: true,
          reason: `[dcg] OMP guard could not resolve the local PTY shell dialect safely: ${describeChildCollectionFailure(err)}`,
        };
      }
    }

    let proc: Bun.ReadableSubprocess;
    try {
      proc = Bun.spawn([
        DCG_BIN,
        "--robot", "test", "--stdin", "--agent", "omp", "--dialect", shellDialect,
        "--format", "json",
        "--omp-bridge-output",
      ], {
        cwd: commandCwd,
        stdin: commandStdin(command),
        stdout: "pipe",
        stderr: "pipe",
        // Bun owns this timer and process reap. SIGKILL makes the ceiling a
        // hard backstop even when a wedged evaluator cannot handle SIGTERM.
        timeout: DCG_CHILD_TIMEOUT_MS,
        killSignal: "SIGKILL",
      });
    } catch (err) {
      console.error(`[dcg] OMP guard could not run dcg: ${describeChildCollectionFailure(err)}`);
      return;
    }

    // Observe each child capability independently under one cleared watchdog.
    // Fail-fast aggregation could erase a completed safety signal; waiting for
    // bare pipe EOF could outlive the direct child when a descendant inherits
    // an fd. The observer preserves retained bytes, bounds the drain, and
    // kills the direct child if exit observation itself faults or stalls.
    const {
      stdoutResult,
      stderrResult,
      exitResult,
      boundary: observationBoundary,
      killFailure: observationKillFailure,
    } = await observeDcgChild(proc);
    const collectionFailures: string[] = [];
    let stdoutText: DcgBoundedText = { text: "", overflowed: false };
    if (stdoutResult.status === "fulfilled") {
      stdoutText = stdoutResult.value;
      if (stdoutText.readFailure) collectionFailures.push(`stdout read failed: ${stdoutText.readFailure}`);
    } else {
      collectionFailures.push(`stdout read failed: ${describeChildCollectionFailure(stdoutResult.reason)}`);
    }
    let stderrText: DcgBoundedText = { text: "", overflowed: false };
    if (stderrResult.status === "fulfilled") {
      stderrText = stderrResult.value;
      if (stderrText.readFailure) collectionFailures.push(`stderr read failed: ${stderrText.readFailure}`);
    } else {
      collectionFailures.push(`stderr read failed: ${describeChildCollectionFailure(stderrResult.reason)}`);
    }
    let exitCode: unknown = undefined;
    if (exitResult.status === "fulfilled") {
      exitCode = exitResult.value;
    } else if (exitResult.reason !== DCG_OBSERVATION_ABORTED) {
      collectionFailures.push(`exit status failed: ${describeChildCollectionFailure(exitResult.reason)}`);
    }
    if (observationBoundary === "pipe-drain") {
      collectionFailures.push(
        `child pipes exceeded the ${DCG_CHILD_PIPE_DRAIN_GRACE_MS}-millisecond post-exit drain grace`,
      );
    } else if (observationBoundary === "hard-deadline") {
      collectionFailures.push(
        `child observation exceeded the ${DCG_CHILD_OBSERVATION_TIMEOUT_MS}-millisecond outer deadline`,
      );
    }
    if (observationKillFailure) {
      collectionFailures.push(`direct-child SIGKILL failed: ${observationKillFailure}`);
    }
    // Bun populates `signalCode` only after termination. Read it after both
    // pipes and `.exited` have independently settled so an early rejection of
    // the exit observation cannot hide a later signal that arrives before EOF.
    // The property is synchronous; retain a throwing getter as its own fault.
    let signalCode: unknown = undefined;
    try {
      signalCode = proc.signalCode;
      if (signalCode !== null && !isDcgSignalCode(signalCode)) {
        // Never echo an invalid runtime value: control characters could forge
        // a diagnostic line. Its type is enough to identify the contract fault.
        collectionFailures.push(`signal status invalid: ${typeof signalCode}`);
      }
    } catch (reason) {
      collectionFailures.push(`signal status failed: ${describeChildCollectionFailure(reason)}`);
    }

    // Treat the two child streams as separate capabilities: stdout alone may
    // carry the robot decision; stderr is diagnostic-only but never discarded.
    // An overflow is itself a conservative block. Never parse a retained JSON
    // prefix: it might be a complete allow followed by a discarded denial.
    const childOutcome = childOutcomeFromTermination(exitCode, signalCode);
    const classification = stdoutText.overflowed
      ? { action: "block" as const, output: { verdict: "unknown" as const } }
      : classifyDcgChild(childOutcome, stdoutText.text);
    const stderrDetail = visibleStderrDetail(stderrText);
    const protocolDetail = stdoutText.overflowed
      ? ""
      : classification.output.framedBlockingWitness
        ? "dcg stdout contained extra or incomplete data around a complete blocking verdict"
        : classification.output.verdict === "malformed"
          ? "dcg stdout was malformed"
          : classification.output.verdict === "unknown"
            ? "dcg stdout carried an unrecognized decision"
            : "";
    if (stdoutText.overflowed) {
      console.error(`[dcg] OMP guard dcg stdout exceeded ${DCG_STDOUT_MAX_BYTES}-byte safety-verdict cap; blocking conservatively`);
    }
    const hasInfrastructureDiagnostic =
      classification.action === "infrastructure" ||
      childOutcome === "exit-other" ||
      isDcgSignalCode(signalCode) ||
      Boolean(protocolDetail) ||
      collectionFailures.length > 0;
    if (hasInfrastructureDiagnostic) {
      const terminationDetail = childTerminationDetail(exitCode, signalCode);
      const details = boundedDiagnosticText([protocolDetail, stderrDetail, ...collectionFailures].filter(Boolean).join("; "));
      console.error(`[dcg] OMP guard infrastructure failure${terminationDetail}${details ? `: ${details}` : ""}`);
      // A collection fault is not allowed to erase a completed deny-like
      // stdout verdict or the independent blocking exit-1 signal.
      if (classification.action !== "block") return;
    }
    if (!hasInfrastructureDiagnostic && stderrDetail) {
      console.error(`[dcg] OMP guard dcg stderr: ${stderrDetail}`);
    }
    if (classification.action === "allow") return;

    const output = classification.output;
    const reason = stdoutText.overflowed
      ? `Blocked by dcg because evaluator stdout exceeded the ${DCG_STDOUT_MAX_BYTES}-byte safety-verdict cap`
      : BLOCKING_DECISIONS.has(output.verdict)
        ? output.reason || "Blocked by dcg"
        : "Blocked by dcg (exit 1 without a blocking decision)";
    const rule = output.ruleId ? `\n\nRule: ${output.ruleId}` : "";
    return { block: true, reason: `${reason}${rule}` };
  });
}
